[http]
    [http.routers]
       [http.routers.placeholdername]
          rule = "Host(`placeholderdashboardhost`)"
          service = "placeholdername"
          entryPoints = ["web-secure"]
		  middlewares = ["placeholdername-caldav-redirect","retry"]
        [http.routers.placeholdername.tls]
          certResolver = "default" # From static configuration
    [http.services]
        [http.services.placeholdername.loadbalancer]
            [[http.services.placeholdername.loadbalancer.servers]]
                url = "http://placeholderurl"
    [http.middlewares]
      [http.middlewares.placeholdername-caldav-redirect.redirectregex]
        permanent = "true"
		regex = "^https://(.*)/.well-known/(card|cal)dav"
		replacement = https://$${1}/remote.php/dav/"