global:
  # Relevant dataset paths, please use the ZFS dataset syntax such as: tank/apps
  dataset:
   # dataset for internal jail config files
   config: tank/test/apps
   # Iocage root dataset
   iocage: tank/iocage
   # Media library dataset
   media: tank/test/library
   # Parent downloads dataset 
   # (is going to contain: Complete and Incomplete datasets for downloads)
   downloads: tank/test/downloads
  jails:
   # jail version to install
   version: 11.3-RELEASE
   # Global pkgs to install in all jails.
   # Please use standard space delimited pkg install syntax.
   pkgs: curl ca_root_nss nano

# Settings for the individual jails
jail:
  # use the same jailname on both sides of this variable example: example
  test10: test10
   # interfaces is optional and will be autmatically replace with vnet0:bridge0 if not present
   interfaces: vnet0:bridge31
   ip4_addr: 192.168.31.99/24
   gateway: 192.168.31.1
   # dhcp: on
   # Jail specific pkgs. 
   # Please use standard space delimited pkg install syntax.
   pkgs: mono mediainfo sqlite3