blueprint:
  mariadb:
    traefik_service_port: 80
    pkgs: mariadb104-server git nginx  php74-session php74-xml php74-ctype php74-openssl php74-filter php74-gd php74-json php74-mysqli php74-mbstring php74-zlib php74-zip php74-bz2 phpMyAdmin5-php74 php74-pdo_mysql php74-mysqli phpMyAdmin5-php74
    vars: root_password
    reqvars: ip4_addr root_password
